#!/bin/bash

# Test for network conection
ping -c 1 8.8.8.8 2>&1 | grep "connect: Network is unreachable" &>/dev/null
if [ $? = 1 ]; then
   echo "<font color=green>Active</font>"
else
   echo "<font color=red>Not connected</font>" 
fi
