#!/bin/bash

function uploadImage {
  url=$(curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" https://imgur.com/api/upload.xml | grep -E -o "<original_image>(.)*</original_image>" | grep -E -o "http://i.imgur.com/[^<]*")
if [ "$?" != "0" ]; then
    zenity --error --text="Could not send screenshot"
    exit
fi 
 /bin/sh -c "exo-open '$url' "
}
if zenity --question --text="This will send  a screenshot to imgur.com online image hosting service. Proceed?"; then
        sleep 0.5
	scrot -u "$HOME/shot.png" 
	uploadImage "$HOME/shot.png"
	rm "$HOME/shot.png"
	notify-send "Done"
fi
