#!/bin/bash
UPFILE="/var/cache/apt/pkgcache.bin"
UPDATES=$(/usr/bin/lite-pkg-count)

update_status() {

  LAST_RUN=`stat -c %y "$UPFILE" | cut -d" " -f1`
  TODAY_DATE=`date +%Y-%m-%d`

  if [ "${LAST_RUN}" != "${TODAY_DATE}" ]; then
    echo " <section class="gradient">Last checked on <font style=\"color: red;\">${LAST_RUN}</font>, <font style=\"color: red;\">${UPDATES} </font> updates available.<button style=\"padding-bottom:0px;padding-left:50pxi\" onclick=\"location.href=('update://')\">Run Updates</button></section>"
  else
    echo " <section class="gradient">Last checked on <font style=\"color: green;\">${LAST_RUN}</font>, <font style=\"color: red;\">${UPDATES} </font> updates available.<button style=\"padding-bottom:0px;padding-left:50pxi\" onclick=\"location.href=('update://')\">Run Updates</button></section>"
  fi

}

check(){

  if [ -f $UPFILE ]; then
    update_status
  else
    echo " <section class="gradient"><font style=\"color: red;\">No record of updates.</font> <button style=\"padding-bottom:0px;padding-left:50pxi\" onclick=\"location.href=('update://')\">Click to Run Updates</button></section>"
  fi

}

check
