#!/bin/bash
UPFILE="/var/lib/apt/periodic/update-success-stamp"

update_status() {

LAST_RUN=`stat -c %y "$UPFILE" | cut -d" " -f1`
TODAY_DATE=`date +%Y-%m-%d`

if [ "${LAST_RUN}" != "${TODAY_DATE}" ]; then
   echo "Last updated on <a style=\"color: red;\" onclick=\"location.href=('update://')\">${LAST_RUN}</a> time to update"
else
  echo "Last updated on <font color="green">${LAST_RUN}</font>"
fi

}

check(){

if [ -f $UPFILE ]; then
   update_status
else
   echo "Updates not been done, Please update soon"
fi

}

check